.TH knotter 1 "" "knotter-0.9.1_devel" Knotter

.SH NAME
Knotter - Interactive Celtic Knot Editor

.SH SYNOPSIS
.B knotter  \-h\fR|\fB\-v\fR|\fB\-l

.B knotter 
[args 
.I file 
.RB [ -o 
.IR output ]
\&...] 
.RI [ qt-options ]


.SH DESCRIPTION
.B Knotter

Knotter is an editor for interlace patterns. Knots drawn with Knotter can be exported as SVG or raster images.

.SH  OPTIONS 

.SS Information
.TP
.B -h\fR, \fB--help
Print help and exit.
.TP
.B -v\fR, \fB--version
Display version information and exit.
.TP
.B -l\fR, \fB--license
Display license and exit.

.SS Output
.TP
.B -o \fIfile\fR, \fB\-\-output \fIfile
Export last loaded file. Format is deducend from the extension.
.TP
.B -a\fR, \fB--antialias
Enable antialiasing for the following exports.
.TP
.B -na\fR, \fB--no-antialias
Disable antialiasing for the following exports.
.TP
.B -g\fR, \fB--graph
Enable graph output for the following exports.
.TP
.B -ng\fR, \fB--no-graph
Disable graph output for the following exports.

.SS Misc
.TP 
.B -b\fR, \fB--no-gui
Don't start the gui after parsing the command line.

.SH AUTHOR
Mattia Basaglia <mattia.basaglia@gmail.com>
