#############################################################################
# Makefile for building: knotter
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Aug 16 21:32:20 2012
# Project:  Knotter.pro
# Template: app
# Command: /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Knotter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Werror -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -I. -I/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/include/QtCore -I/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/include/QtGui -I/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/include/QtXml -I/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/include/QtSvg -I/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/lib -lQtSvg -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		knot_window.cpp \
		knotview.cpp \
		node.cpp \
		edge.cpp \
		knotgraph.cpp \
		style_dialog.cpp \
		knot_curve_style.cpp \
		clipboard.cpp \
		config_dialog.cpp \
		snapping_grid.cpp \
		gridconfig.cpp moc_knot_window.cpp \
		moc_knotview.cpp \
		moc_style_dialog.cpp \
		moc_color_widget.cpp \
		moc_config_dialog.cpp \
		moc_gridconfig.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		knot_window.o \
		knotview.o \
		node.o \
		edge.o \
		knotgraph.o \
		style_dialog.o \
		knot_curve_style.o \
		clipboard.o \
		config_dialog.o \
		snapping_grid.o \
		gridconfig.o \
		moc_knot_window.o \
		moc_knotview.o \
		moc_style_dialog.o \
		moc_color_widget.o \
		moc_config_dialog.o \
		moc_gridconfig.o \
		qrc_icons.o
DIST          = /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		Knotter.pro
QMAKE_TARGET  = knotter
DESTDIR       = 
TARGET        = knotter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_knot_window.h ui_style_dialog.h ui_config_dialog.h ui_gridconfig.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Knotter.pro  /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Knotter.pro
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Knotter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/knotter0.2.0 || $(MKDIR) .tmp/knotter0.2.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/knotter0.2.0/ && $(COPY_FILE) --parents knot_window.hpp knotview.hpp node.hpp edge.hpp commands.hpp custom_item.hpp knotgraph.hpp style_dialog.hpp color_widget.hpp knot_curve_style.hpp clipboard.hpp config_dialog.hpp snapping_grid.hpp gridconfig.hpp .tmp/knotter0.2.0/ && $(COPY_FILE) --parents icons.qrc .tmp/knotter0.2.0/ && $(COPY_FILE) --parents main.cpp knot_window.cpp knotview.cpp node.cpp edge.cpp knotgraph.cpp style_dialog.cpp knot_curve_style.cpp clipboard.cpp config_dialog.cpp snapping_grid.cpp gridconfig.cpp .tmp/knotter0.2.0/ && $(COPY_FILE) --parents knot_window.ui style_dialog.ui config_dialog.ui gridconfig.ui .tmp/knotter0.2.0/ && $(COPY_FILE) --parents knotter_it.ts .tmp/knotter0.2.0/ && (cd `dirname .tmp/knotter0.2.0` && $(TAR) knotter0.2.0.tar knotter0.2.0 && $(COMPRESS) knotter0.2.0.tar) && $(MOVE) `dirname .tmp/knotter0.2.0`/knotter0.2.0.tar.gz . && $(DEL_FILE) -r .tmp/knotter0.2.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mydist: knotter
	( $(CHK_DIR_EXISTS) .tmp/knotter-0.2.0 || $(MKDIR) .tmp/knotter-0.2.0 ) && $(COPY_FILE) --parents knot_window.ui style_dialog.ui config_dialog.ui gridconfig.ui COPYING README Doxyfile img/logo.svg img/link.svg img/icon.png img/edit_nodes.svg img/edit_edges.svg img/edge_list.svg img/merge.svg icons.qrc Makefile Knotter.pro `ls *.hpp *.cpp *.h` .tmp/knotter-0.2.0 && ( cd `dirname .tmp/knotter-0.2.0` && $(TAR) knotter-0.2.0.tar knotter-0.2.0 && $(COMPRESS) knotter-0.2.0.tar ) && $(MOVE) `dirname .tmp/knotter-0.2.0`/knotter-0.2.0.tar.gz knotter-0.2.0.tar.gz && $(DEL_FILE) -r .tmp/knotter-0.2.0

mydistclean: clean
	$(DEL_FILE) knotter-0.2.0.tar.gz Makefile

doc: knotter Doxyfile
	doxygen

Doxyfile:
	doxygen -g

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_knot_window.cpp moc_knotview.cpp moc_style_dialog.cpp moc_color_widget.cpp moc_config_dialog.cpp moc_gridconfig.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_knot_window.cpp moc_knotview.cpp moc_style_dialog.cpp moc_color_widget.cpp moc_config_dialog.cpp moc_gridconfig.cpp
moc_knot_window.cpp: ui_knot_window.h \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp \
		style_dialog.hpp \
		ui_style_dialog.h \
		color_widget.hpp \
		clipboard.hpp \
		knot_window.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) knot_window.hpp -o moc_knot_window.cpp

moc_knotview.cpp: node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp \
		knotview.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) knotview.hpp -o moc_knotview.cpp

moc_style_dialog.cpp: ui_style_dialog.h \
		color_widget.hpp \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp \
		style_dialog.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) style_dialog.hpp -o moc_style_dialog.cpp

moc_color_widget.cpp: color_widget.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) color_widget.hpp -o moc_color_widget.cpp

moc_config_dialog.cpp: ui_config_dialog.h \
		config_dialog.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) config_dialog.hpp -o moc_config_dialog.cpp

moc_gridconfig.cpp: ui_gridconfig.h \
		snapping_grid.hpp \
		gridconfig.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) gridconfig.hpp -o moc_gridconfig.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		img/edit_nodes.svg \
		img/logo.svg \
		img/link.svg \
		img/merge.svg \
		img/edit_edges.svg \
		img/edge_list.svg
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_knot_window.h ui_style_dialog.h ui_config_dialog.h ui_gridconfig.h
compiler_uic_clean:
	-$(DEL_FILE) ui_knot_window.h ui_style_dialog.h ui_config_dialog.h ui_gridconfig.h
ui_knot_window.h: knot_window.ui \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/uic knot_window.ui -o ui_knot_window.h

ui_style_dialog.h: style_dialog.ui \
		color_widget.hpp \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/uic style_dialog.ui -o ui_style_dialog.h

ui_config_dialog.h: config_dialog.ui
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/uic config_dialog.ui -o ui_config_dialog.h

ui_gridconfig.h: gridconfig.ui
	/home/bazzy/share/qt_sdk/Desktop/Qt/4.8.0/gcc/bin/uic gridconfig.ui -o ui_gridconfig.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp knot_window.hpp \
		ui_knot_window.h \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp \
		style_dialog.hpp \
		ui_style_dialog.h \
		color_widget.hpp \
		clipboard.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

knot_window.o: knot_window.cpp knot_window.hpp \
		ui_knot_window.h \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp \
		style_dialog.hpp \
		ui_style_dialog.h \
		color_widget.hpp \
		clipboard.hpp \
		commands.hpp \
		gridconfig.hpp \
		ui_gridconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knot_window.o knot_window.cpp

knotview.o: knotview.cpp knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp \
		commands.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotview.o knotview.cpp

node.o: node.cpp node.hpp \
		custom_item.hpp \
		edge.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

edge.o: edge.cpp edge.hpp \
		custom_item.hpp \
		node.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o edge.cpp

knotgraph.o: knotgraph.cpp knotgraph.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knot_curve_style.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotgraph.o knotgraph.cpp

style_dialog.o: style_dialog.cpp style_dialog.hpp \
		ui_style_dialog.h \
		color_widget.hpp \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o style_dialog.o style_dialog.cpp

knot_curve_style.o: knot_curve_style.cpp knot_curve_style.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knot_curve_style.o knot_curve_style.cpp

clipboard.o: clipboard.cpp clipboard.hpp \
		knotview.hpp \
		node.hpp \
		custom_item.hpp \
		edge.hpp \
		knotgraph.hpp \
		knot_curve_style.hpp \
		snapping_grid.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipboard.o clipboard.cpp

config_dialog.o: config_dialog.cpp config_dialog.hpp \
		ui_config_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config_dialog.o config_dialog.cpp

snapping_grid.o: snapping_grid.cpp snapping_grid.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snapping_grid.o snapping_grid.cpp

gridconfig.o: gridconfig.cpp gridconfig.hpp \
		ui_gridconfig.h \
		snapping_grid.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridconfig.o gridconfig.cpp

moc_knot_window.o: moc_knot_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knot_window.o moc_knot_window.cpp

moc_knotview.o: moc_knotview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotview.o moc_knotview.cpp

moc_style_dialog.o: moc_style_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_style_dialog.o moc_style_dialog.cpp

moc_color_widget.o: moc_color_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_color_widget.o moc_color_widget.cpp

moc_config_dialog.o: moc_config_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config_dialog.o moc_config_dialog.cpp

moc_gridconfig.o: moc_gridconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gridconfig.o moc_gridconfig.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

