#############################################################################
# Makefile for building: knotter
# Generated by qmake (2.01a) (Qt 4.7.4) on: Fri Aug 17 19:24:04 2012
# Project:  Knotter.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Knotter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -Werror -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSvg -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		knot_window.cpp \
		error_recovery.cpp \
		dialogs/style_dialog.cpp \
		dialogs/config_dialog.cpp \
		dialogs/gridconfig.cpp \
		graphics/knotview.cpp \
		graphics/node.cpp \
		graphics/edge.cpp \
		graphics/knotgraph.cpp \
		graphics/knot_curve_style.cpp \
		graphics/clipboard.cpp \
		graphics/snapping_grid.cpp moc_knot_window.cpp \
		moc_color_widget.cpp \
		moc_style_dialog.cpp \
		moc_config_dialog.cpp \
		moc_gridconfig.cpp \
		moc_knotview.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		knot_window.o \
		error_recovery.o \
		style_dialog.o \
		config_dialog.o \
		gridconfig.o \
		knotview.o \
		node.o \
		edge.o \
		knotgraph.o \
		knot_curve_style.o \
		clipboard.o \
		snapping_grid.o \
		moc_knot_window.o \
		moc_color_widget.o \
		moc_style_dialog.o \
		moc_config_dialog.o \
		moc_gridconfig.o \
		moc_knotview.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		dialogs/dialogs.pri \
		graphics/graphics.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Knotter.pro
QMAKE_TARGET  = knotter
DESTDIR       = 
TARGET        = knotter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_knot_window.h ui_style_dialog.h ui_config_dialog.h ui_gridconfig.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Knotter.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		dialogs/dialogs.pri \
		graphics/graphics.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Knotter.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
dialogs/dialogs.pri:
graphics/graphics.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Knotter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/knotter0.3.5 || $(MKDIR) .tmp/knotter0.3.5 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/knotter0.3.5/ && $(COPY_FILE) --parents knot_window.hpp color_widget.hpp error_recovery.hpp dialogs/style_dialog.hpp dialogs/config_dialog.hpp dialogs/gridconfig.hpp graphics/knotview.hpp graphics/node.hpp graphics/edge.hpp graphics/commands.hpp graphics/custom_item.hpp graphics/knotgraph.hpp graphics/knot_curve_style.hpp graphics/clipboard.hpp graphics/snapping_grid.hpp graphics/grid_scene.hpp .tmp/knotter0.3.5/ && $(COPY_FILE) --parents icons.qrc .tmp/knotter0.3.5/ && $(COPY_FILE) --parents main.cpp knot_window.cpp error_recovery.cpp dialogs/style_dialog.cpp dialogs/config_dialog.cpp dialogs/gridconfig.cpp graphics/knotview.cpp graphics/node.cpp graphics/edge.cpp graphics/knotgraph.cpp graphics/knot_curve_style.cpp graphics/clipboard.cpp graphics/snapping_grid.cpp .tmp/knotter0.3.5/ && $(COPY_FILE) --parents knot_window.ui dialogs/style_dialog.ui dialogs/config_dialog.ui dialogs/gridconfig.ui .tmp/knotter0.3.5/ && $(COPY_FILE) --parents knotter_it.ts .tmp/knotter0.3.5/ && (cd `dirname .tmp/knotter0.3.5` && $(TAR) knotter0.3.5.tar knotter0.3.5 && $(COMPRESS) knotter0.3.5.tar) && $(MOVE) `dirname .tmp/knotter0.3.5`/knotter0.3.5.tar.gz . && $(DEL_FILE) -r .tmp/knotter0.3.5


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mydist: knotter
	( $(CHK_DIR_EXISTS) .tmp/knotter-0.3.5 || $(MKDIR) .tmp/knotter-0.3.5 ) && $(COPY_FILE) -r --parents COPYING README Doxyfile NEWS icons.qrc Makefile Knotter.pro `ls *.hpp *.cpp *.ui ` dialogs img graphics .tmp/knotter-0.3.5 && ( cd `dirname .tmp/knotter-0.3.5` && $(TAR) knotter-0.3.5.tar knotter-0.3.5 && $(COMPRESS) knotter-0.3.5.tar ) && $(MOVE) `dirname .tmp/knotter-0.3.5`/knotter-0.3.5.tar.gz knotter-0.3.5.tar.gz && $(DEL_FILE) -r .tmp/knotter-0.3.5

mydistclean: clean
	$(DEL_FILE) knotter-0.3.5.tar.gz Makefile

doc: knotter Doxyfile
	doxygen

Doxyfile:
	doxygen -g

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_knot_window.cpp moc_color_widget.cpp moc_style_dialog.cpp moc_config_dialog.cpp moc_gridconfig.cpp moc_knotview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_knot_window.cpp moc_color_widget.cpp moc_style_dialog.cpp moc_config_dialog.cpp moc_gridconfig.cpp moc_knotview.cpp
moc_knot_window.cpp: ui_knot_window.h \
		dialogs/style_dialog.hpp \
		ui_style_dialog.h \
		graphics/clipboard.hpp \
		graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp \
		knot_window.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knot_window.hpp -o moc_knot_window.cpp

moc_color_widget.cpp: color_widget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) color_widget.hpp -o moc_color_widget.cpp

moc_style_dialog.cpp: ui_style_dialog.h \
		dialogs/style_dialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogs/style_dialog.hpp -o moc_style_dialog.cpp

moc_config_dialog.cpp: ui_config_dialog.h \
		dialogs/config_dialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogs/config_dialog.hpp -o moc_config_dialog.cpp

moc_gridconfig.cpp: ui_gridconfig.h \
		graphics/snapping_grid.hpp \
		dialogs/gridconfig.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogs/gridconfig.hpp -o moc_gridconfig.cpp

moc_knotview.cpp: graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp \
		graphics/knotview.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) graphics/knotview.hpp -o moc_knotview.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		img/logo.svg \
		img/vflip.svg \
		img/triangular_grid.svg \
		img/line_no.svg \
		img/line_dash_dot.svg \
		img/ogee.svg \
		img/merge.svg \
		img/line_dot.svg \
		img/line_dash.svg \
		img/hflip.svg \
		img/poly.svg \
		img/square_grid.svg \
		img/triangular_grid2.svg \
		img/pointpoly.svg \
		img/move_grid.svg \
		img/link.svg \
		img/edit_nodes.svg \
		img/edit_edges.svg \
		img/line_solid.svg \
		img/pointcurve.svg \
		img/edge_list.svg
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_knot_window.h ui_style_dialog.h ui_config_dialog.h ui_gridconfig.h
compiler_uic_clean:
	-$(DEL_FILE) ui_knot_window.h ui_style_dialog.h ui_config_dialog.h ui_gridconfig.h
ui_knot_window.h: knot_window.ui \
		graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp
	/usr/bin/uic-qt4 knot_window.ui -o ui_knot_window.h

ui_style_dialog.h: dialogs/style_dialog.ui \
		graphics/knotview.hpp \
		color_widget.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp
	/usr/bin/uic-qt4 dialogs/style_dialog.ui -o ui_style_dialog.h

ui_config_dialog.h: dialogs/config_dialog.ui
	/usr/bin/uic-qt4 dialogs/config_dialog.ui -o ui_config_dialog.h

ui_gridconfig.h: dialogs/gridconfig.ui
	/usr/bin/uic-qt4 dialogs/gridconfig.ui -o ui_gridconfig.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp knot_window.hpp \
		ui_knot_window.h \
		dialogs/style_dialog.hpp \
		ui_style_dialog.h \
		graphics/clipboard.hpp \
		graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp \
		error_recovery.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

knot_window.o: knot_window.cpp knot_window.hpp \
		ui_knot_window.h \
		dialogs/style_dialog.hpp \
		ui_style_dialog.h \
		graphics/clipboard.hpp \
		graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp \
		graphics/commands.hpp \
		dialogs/gridconfig.hpp \
		ui_gridconfig.h \
		error_recovery.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knot_window.o knot_window.cpp

error_recovery.o: error_recovery.cpp error_recovery.hpp \
		graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o error_recovery.o error_recovery.cpp

style_dialog.o: dialogs/style_dialog.cpp dialogs/style_dialog.hpp \
		ui_style_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o style_dialog.o dialogs/style_dialog.cpp

config_dialog.o: dialogs/config_dialog.cpp dialogs/config_dialog.hpp \
		ui_config_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config_dialog.o dialogs/config_dialog.cpp

gridconfig.o: dialogs/gridconfig.cpp dialogs/gridconfig.hpp \
		ui_gridconfig.h \
		graphics/snapping_grid.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridconfig.o dialogs/gridconfig.cpp

knotview.o: graphics/knotview.cpp graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp \
		graphics/commands.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotview.o graphics/knotview.cpp

node.o: graphics/node.cpp graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o graphics/node.cpp

edge.o: graphics/edge.cpp graphics/edge.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/node.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o graphics/edge.cpp

knotgraph.o: graphics/knotgraph.cpp graphics/knotgraph.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knot_curve_style.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotgraph.o graphics/knotgraph.cpp

knot_curve_style.o: graphics/knot_curve_style.cpp graphics/knot_curve_style.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knot_curve_style.o graphics/knot_curve_style.cpp

clipboard.o: graphics/clipboard.cpp graphics/clipboard.hpp \
		graphics/knotview.hpp \
		graphics/node.hpp \
		graphics/custom_item.hpp \
		graphics/grid_scene.hpp \
		graphics/snapping_grid.hpp \
		graphics/edge.hpp \
		graphics/knotgraph.hpp \
		graphics/knot_curve_style.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipboard.o graphics/clipboard.cpp

snapping_grid.o: graphics/snapping_grid.cpp graphics/snapping_grid.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snapping_grid.o graphics/snapping_grid.cpp

moc_knot_window.o: moc_knot_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knot_window.o moc_knot_window.cpp

moc_color_widget.o: moc_color_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_color_widget.o moc_color_widget.cpp

moc_style_dialog.o: moc_style_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_style_dialog.o moc_style_dialog.cpp

moc_config_dialog.o: moc_config_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config_dialog.o moc_config_dialog.cpp

moc_gridconfig.o: moc_gridconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gridconfig.o moc_gridconfig.cpp

moc_knotview.o: moc_knotview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotview.o moc_knotview.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

