#############################################################################
# Makefile for building: knotter
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat Aug 18 00:34:35 2012
# Project:  Knotter.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Knotter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -Isrc/dialogs -Iinclude -Isrc/generated -Isrc/generated
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSvg -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/error_recovery.cpp \
		src/dialogs/style_dialog.cpp \
		src/dialogs/knot_window.cpp \
		src/dialogs/gridconfig.cpp \
		src/dialogs/config_dialog.cpp \
		src/graphics/node.cpp \
		src/graphics/knotview.cpp \
		src/graphics/knotgraph.cpp \
		src/graphics/knot_curve_style.cpp \
		src/graphics/edge.cpp \
		src/graphics/clipboard.cpp \
		src/graphics/snapping_grid.cpp src/generated/moc_style_dialog.cpp \
		src/generated/moc_knot_window.cpp \
		src/generated/moc_gridconfig.cpp \
		src/generated/moc_config_dialog.cpp \
		src/generated/moc_knotview.cpp \
		src/generated/moc_color_widget.cpp \
		src/generated/qrc_icons.cpp
OBJECTS       = main.o \
		error_recovery.o \
		style_dialog.o \
		knot_window.o \
		gridconfig.o \
		config_dialog.o \
		node.o \
		knotview.o \
		knotgraph.o \
		knot_curve_style.o \
		edge.o \
		clipboard.o \
		snapping_grid.o \
		moc_style_dialog.o \
		moc_knot_window.o \
		moc_gridconfig.o \
		moc_config_dialog.o \
		moc_knotview.o \
		moc_color_widget.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		src/dialogs/dialogs.pri \
		src/graphics/graphics.pri \
		src/src.pri \
		include/include.pri \
		img/img.pri \
		translations/translations.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Knotter.pro
QMAKE_TARGET  = knotter
DESTDIR       = 
TARGET        = knotter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/generated/ui_knot_window.h src/generated/ui_gridconfig.h src/generated/ui_config_dialog.h src/generated/ui_style_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Knotter.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		src/dialogs/dialogs.pri \
		src/graphics/graphics.pri \
		src/src.pri \
		include/include.pri \
		img/img.pri \
		translations/translations.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Knotter.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
src/dialogs/dialogs.pri:
src/graphics/graphics.pri:
src/src.pri:
include/include.pri:
img/img.pri:
translations/translations.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Knotter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/knotter0.3.5 || $(MKDIR) .tmp/knotter0.3.5 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/knotter0.3.5/ && $(COPY_FILE) --parents src/dialogs/style_dialog.hpp src/dialogs/knot_window.hpp src/dialogs/gridconfig.hpp src/dialogs/config_dialog.hpp include/snapping_grid.hpp include/knotview.hpp include/node.hpp include/knotgraph.hpp include/knot_curve_style.hpp include/grid_scene.hpp include/error_recovery.hpp include/edge.hpp include/custom_item.hpp include/commands.hpp include/color_widget.hpp include/clipboard.hpp .tmp/knotter0.3.5/ && $(COPY_FILE) --parents img/icons.qrc .tmp/knotter0.3.5/ && $(COPY_FILE) --parents src/main.cpp src/error_recovery.cpp src/dialogs/style_dialog.cpp src/dialogs/knot_window.cpp src/dialogs/gridconfig.cpp src/dialogs/config_dialog.cpp src/graphics/node.cpp src/graphics/knotview.cpp src/graphics/knotgraph.cpp src/graphics/knot_curve_style.cpp src/graphics/edge.cpp src/graphics/clipboard.cpp src/graphics/snapping_grid.cpp .tmp/knotter0.3.5/ && $(COPY_FILE) --parents src/dialogs/knot_window.ui src/dialogs/gridconfig.ui src/dialogs/config_dialog.ui src/dialogs/style_dialog.ui .tmp/knotter0.3.5/ && $(COPY_FILE) --parents translations/knotter_it.ts .tmp/knotter0.3.5/ && (cd `dirname .tmp/knotter0.3.5` && $(TAR) knotter0.3.5.tar knotter0.3.5 && $(COMPRESS) knotter0.3.5.tar) && $(MOVE) `dirname .tmp/knotter0.3.5`/knotter0.3.5.tar.gz . && $(DEL_FILE) -r .tmp/knotter0.3.5


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mydist: knotter
	( $(CHK_DIR_EXISTS) .tmp/knotter-0.3.5 || $(MKDIR) .tmp/knotter-0.3.5 ) && $(COPY_FILE) --parents COPYING README Doxyfile NEWS Makefile Knotter.pro .tmp/knotter-0.3.5 && $(COPY_DIR) --parents src include img .tmp/knotter-0.3.5 && ( cd `dirname .tmp/knotter-0.3.5` && $(TAR) knotter-0.3.5.tar knotter-0.3.5 && $(COMPRESS) knotter-0.3.5.tar ) && $(MOVE) `dirname .tmp/knotter-0.3.5`/knotter-0.3.5.tar.gz knotter-0.3.5.tar.gz && $(DEL_FILE) -r .tmp/knotter-0.3.5

mydistclean: clean
	$(DEL_FILE) knotter-0.3.5.tar.gz Makefile

doc: knotter Doxyfile
	doxygen

Doxyfile:
	doxygen -g

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: src/generated/moc_style_dialog.cpp src/generated/moc_knot_window.cpp src/generated/moc_gridconfig.cpp src/generated/moc_config_dialog.cpp src/generated/moc_knotview.cpp src/generated/moc_color_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) src/generated/moc_style_dialog.cpp src/generated/moc_knot_window.cpp src/generated/moc_gridconfig.cpp src/generated/moc_config_dialog.cpp src/generated/moc_knotview.cpp src/generated/moc_color_widget.cpp
src/generated/moc_style_dialog.cpp: src/generated/ui_style_dialog.h \
		src/dialogs/style_dialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/style_dialog.hpp -o src/generated/moc_style_dialog.cpp

src/generated/moc_knot_window.cpp: src/generated/ui_knot_window.h \
		src/dialogs/style_dialog.hpp \
		src/generated/ui_style_dialog.h \
		src/dialogs/knot_window.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/knot_window.hpp -o src/generated/moc_knot_window.cpp

src/generated/moc_gridconfig.cpp: src/generated/ui_gridconfig.h \
		src/dialogs/gridconfig.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/gridconfig.hpp -o src/generated/moc_gridconfig.cpp

src/generated/moc_config_dialog.cpp: src/generated/ui_config_dialog.h \
		src/dialogs/config_dialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/config_dialog.hpp -o src/generated/moc_config_dialog.cpp

src/generated/moc_knotview.cpp: include/node.hpp \
		include/custom_item.hpp \
		include/grid_scene.hpp \
		include/snapping_grid.hpp \
		include/edge.hpp \
		include/knotgraph.hpp \
		include/knot_curve_style.hpp \
		include/knotview.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/knotview.hpp -o src/generated/moc_knotview.cpp

src/generated/moc_color_widget.cpp: include/color_widget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/color_widget.hpp -o src/generated/moc_color_widget.cpp

compiler_rcc_make_all: src/generated/qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) src/generated/qrc_icons.cpp
src/generated/qrc_icons.cpp: img/icons.qrc \
		img/logo.svg \
		img/vflip.svg \
		img/triangular_grid.svg \
		img/line_no.svg \
		img/line_dash_dot.svg \
		img/ogee.svg \
		img/merge.svg \
		img/line_dot.svg \
		img/line_dash.svg \
		img/hflip.svg \
		img/poly.svg \
		img/icon.png \
		img/square_grid.svg \
		img/triangular_grid2.svg \
		img/pointpoly.svg \
		img/move_grid.svg \
		img/link.svg \
		img/edit_nodes.svg \
		img/edit_edges.svg \
		img/line_solid.svg \
		img/pointcurve.svg \
		img/edge_list.svg \
		img/logo_big.svg
	/usr/bin/rcc -name icons img/icons.qrc -o src/generated/qrc_icons.cpp

compiler_image_collection_make_all: src/generated/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) src/generated/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/generated/ui_knot_window.h src/generated/ui_gridconfig.h src/generated/ui_config_dialog.h src/generated/ui_style_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) src/generated/ui_knot_window.h src/generated/ui_gridconfig.h src/generated/ui_config_dialog.h src/generated/ui_style_dialog.h
src/generated/ui_knot_window.h: src/dialogs/knot_window.ui
	/usr/bin/uic-qt4 src/dialogs/knot_window.ui -o src/generated/ui_knot_window.h

src/generated/ui_gridconfig.h: src/dialogs/gridconfig.ui
	/usr/bin/uic-qt4 src/dialogs/gridconfig.ui -o src/generated/ui_gridconfig.h

src/generated/ui_config_dialog.h: src/dialogs/config_dialog.ui
	/usr/bin/uic-qt4 src/dialogs/config_dialog.ui -o src/generated/ui_config_dialog.h

src/generated/ui_style_dialog.h: src/dialogs/style_dialog.ui
	/usr/bin/uic-qt4 src/dialogs/style_dialog.ui -o src/generated/ui_style_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

error_recovery.o: src/error_recovery.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o error_recovery.o src/error_recovery.cpp

style_dialog.o: src/dialogs/style_dialog.cpp src/dialogs/style_dialog.hpp \
		src/generated/ui_style_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o style_dialog.o src/dialogs/style_dialog.cpp

knot_window.o: src/dialogs/knot_window.cpp src/dialogs/knot_window.hpp \
		src/generated/ui_knot_window.h \
		src/dialogs/style_dialog.hpp \
		src/generated/ui_style_dialog.h \
		src/dialogs/gridconfig.hpp \
		src/generated/ui_gridconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knot_window.o src/dialogs/knot_window.cpp

gridconfig.o: src/dialogs/gridconfig.cpp src/dialogs/gridconfig.hpp \
		src/generated/ui_gridconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridconfig.o src/dialogs/gridconfig.cpp

config_dialog.o: src/dialogs/config_dialog.cpp src/dialogs/config_dialog.hpp \
		src/generated/ui_config_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config_dialog.o src/dialogs/config_dialog.cpp

node.o: src/graphics/node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o src/graphics/node.cpp

knotview.o: src/graphics/knotview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotview.o src/graphics/knotview.cpp

knotgraph.o: src/graphics/knotgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotgraph.o src/graphics/knotgraph.cpp

knot_curve_style.o: src/graphics/knot_curve_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knot_curve_style.o src/graphics/knot_curve_style.cpp

edge.o: src/graphics/edge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o src/graphics/edge.cpp

clipboard.o: src/graphics/clipboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipboard.o src/graphics/clipboard.cpp

snapping_grid.o: src/graphics/snapping_grid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snapping_grid.o src/graphics/snapping_grid.cpp

moc_style_dialog.o: src/generated/moc_style_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_style_dialog.o src/generated/moc_style_dialog.cpp

moc_knot_window.o: src/generated/moc_knot_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knot_window.o src/generated/moc_knot_window.cpp

moc_gridconfig.o: src/generated/moc_gridconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gridconfig.o src/generated/moc_gridconfig.cpp

moc_config_dialog.o: src/generated/moc_config_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config_dialog.o src/generated/moc_config_dialog.cpp

moc_knotview.o: src/generated/moc_knotview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotview.o src/generated/moc_knotview.cpp

moc_color_widget.o: src/generated/moc_color_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_color_widget.o src/generated/moc_color_widget.cpp

qrc_icons.o: src/generated/qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o src/generated/qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

