Knotter: StyleDialog Class Reference
StyleDialog Class Reference
#include <style_dialog.hpp>
Public Slots
void clicked (QAbstractButton *button)
Signals
void changed ()
emitted when values have been changed and need to be applied
Public Member Functions
StyleDialog (QWidget *parent=0)
knot_curve_styler::style_id get_style_id () const
void set_style_id (knot_curve_styler::style_id)
Qt::PenJoinStyle get_join_style () const
void set_join_style (Qt::PenJoinStyle pjs)
Private Slots
void on_knot_width_spinner_valueChanged (double arg1)
void on_outline_width_spinner_valueChanged (double arg1)
void on_color_color_changed (const QColor &)
void on_outline_color_color_changed (const QColor &)
void on_style_combo_activated (int index)
void on_cusp_angle_spinner_valueChanged (double arg1)
void on_handle_length_spinner_valueChanged (double arg1)
void on_crossing_gap_spinner_valueChanged (double arg1)
void on_point_combo_activated (int index)
Private Attributes
QMap
< knot_curve_styler::style_id,
int > combo_style
knot_curve_styler::style_id curstyle
Friends
class Knot_Window
Detailed Description
Definition at line 31 of file style_dialog.hpp.
Constructor & Destructor Documentation
StyleDialog::StyleDialog (QWidget * parent = 0) [explicit]
Todo:
PenStyle
Definition at line 31 of file style_dialog.cpp.
Member Function Documentation
void StyleDialog::changed () [signal]
emitted when values have been changed and need to be applied
Definition at line 127 of file moc_style_dialog.cpp.
Referenced by clicked().
void StyleDialog::clicked (QAbstractButton * button) [slot]
Definition at line 69 of file style_dialog.cpp.
Qt::PenJoinStyle StyleDialog::get_join_style () const
Definition at line 135 of file style_dialog.cpp.
Referenced by Knot_Window::apply_style().
knot_curve_styler::style_id StyleDialog::get_style_id () const
Definition at line 56 of file style_dialog.cpp.
Referenced by Knot_Window::apply_style().
void StyleDialog::on_color_color_changed (const QColor & c) [private, slot]
Definition at line 88 of file style_dialog.cpp.
void StyleDialog::on_crossing_gap_spinner_valueChanged (double arg1) [private, slot]
Definition at line 119 of file style_dialog.cpp.
void StyleDialog::on_cusp_angle_spinner_valueChanged (double arg1) [private, slot]
Definition at line 109 of file style_dialog.cpp.
void StyleDialog::on_handle_length_spinner_valueChanged (double arg1) [private, slot]
Definition at line 114 of file style_dialog.cpp.
void StyleDialog::on_knot_width_spinner_valueChanged (double arg1) [private, slot]
Definition at line 76 of file style_dialog.cpp.
void StyleDialog::on_outline_color_color_changed (const QColor & c) [private, slot]
Definition at line 95 of file style_dialog.cpp.
void StyleDialog::on_outline_width_spinner_valueChanged (double arg1) [private, slot]
Definition at line 81 of file style_dialog.cpp.
void StyleDialog::on_point_combo_activated (int index) [private, slot]
Definition at line 124 of file style_dialog.cpp.
void StyleDialog::on_style_combo_activated (int index) [private, slot]
Definition at line 103 of file style_dialog.cpp.
void StyleDialog::set_join_style (Qt::PenJoinStyle pjs)
Definition at line 148 of file style_dialog.cpp.
Referenced by Knot_Window::update_style_dialog().
void StyleDialog::set_style_id (knot_curve_styler::style_id sid)
Definition at line 61 of file style_dialog.cpp.
Referenced by Knot_Window::update_style_dialog().
Friends And Related Function Documentation
friend class Knot_Window [friend]
Definition at line 36 of file style_dialog.hpp.
Member Data Documentation
QMap<knot_curve_styler::style_id,int> StyleDialog::combo_style [private]
Definition at line 37 of file style_dialog.hpp.
Referenced by on_style_combo_activated(), set_style_id(), and StyleDialog().
knot_curve_styler::style_id StyleDialog::curstyle [private]
Definition at line 38 of file style_dialog.hpp.
Referenced by get_style_id(), on_style_combo_activated(), and set_style_id().
The documentation for this class was generated from the following files:
style_dialog.hpp
moc_style_dialog.cpp
style_dialog.cpp