Knotter: KnotGraph Class Reference
KnotGraph Class Reference
#include <knotgraph.hpp>
Public Member Functions
KnotGraph ()
~KnotGraph ()
void add_node (Node *which)
void add_edge (Edge *which)
void remove_node (Node *which)
void remove_edge (Edge *which)
void add (CustomItem *what)
void clear ()
QPainterPath build ()
void set_width (double w)
set knot path width
double get_width () const
get knot path width
knot_curve_styler::style_id get_curve_style () const
void set_curve_style (knot_curve_styler::style_id)
double get_cusp_angle () const
void set_cusp_angle (double ca)
double get_handle_length () const
void set_handle_length (double hl)
double get_crossing_distance () const
void set_crossing_distance (double cd)
Qt::PenJoinStyle get_join_style () const
void set_join_style (Qt::PenJoinStyle)
Protected Attributes
QPainterPath knot
QList< Node * > nodes
QList< Edge * > edges
QList< Edge * > traversed_edges
QPainterPathStroker stroker
knot_curve_styler::style_id curve_style
double cusp_angle
double handle_length
double crossing_distance
Detailed Description
Definition at line 34 of file knotgraph.hpp.
Constructor & Destructor Documentation
KnotGraph::KnotGraph ()
Todo:
configure miter limit
Todo:
allow per-node style: if NULL use default else use node setup (?)
Definition at line 29 of file knotgraph.cpp.
KnotGraph::~KnotGraph ()
Definition at line 44 of file knotgraph.cpp.
Member Function Documentation
void KnotGraph::add (CustomItem * what)
Definition at line 70 of file knotgraph.cpp.
void KnotGraph::add_edge (Edge * which)
Definition at line 54 of file knotgraph.cpp.
Referenced by add(), and KnotView::link().
void KnotGraph::add_node (Node * which)
Definition at line 48 of file knotgraph.cpp.
Referenced by add(), and KnotView::do_add_node().
QPainterPath KnotGraph::build ()
Definition at line 82 of file knotgraph.cpp.
Referenced by KnotView::mouseMoveEvent(), and KnotView::redraw().
void KnotGraph::clear ()
Definition at line 76 of file knotgraph.cpp.
Referenced by KnotView::clear().
double KnotGraph::get_crossing_distance () const
Definition at line 177 of file knotgraph.cpp.
Referenced by KnotView::get_crossing_distance(), and KnotView::writeXML().
knot_curve_styler::style_id KnotGraph::get_curve_style () const
Definition at line 147 of file knotgraph.cpp.
Referenced by KnotView::get_curve_style(), and KnotView::writeXML().
double KnotGraph::get_cusp_angle () const
Definition at line 157 of file knotgraph.cpp.
Referenced by KnotView::get_cusp_angle(), and KnotView::writeXML().
double KnotGraph::get_handle_length () const
Definition at line 167 of file knotgraph.cpp.
Referenced by KnotView::get_handle_length(), and KnotView::writeXML().
Qt::PenJoinStyle KnotGraph::get_join_style () const
Definition at line 187 of file knotgraph.cpp.
Referenced by KnotView::get_join_style(), and KnotView::writeXML().
double KnotGraph::get_width () const
get knot path width
Definition at line 142 of file knotgraph.cpp.
Referenced by KnotView::get_width().
void KnotGraph::remove_edge (Edge * which)
Definition at line 65 of file knotgraph.cpp.
Referenced by KnotView::do_remove_node(), and KnotView::unlink().
void KnotGraph::remove_node (Node * which)
Definition at line 60 of file knotgraph.cpp.
Referenced by KnotView::do_remove_node().
void KnotGraph::set_crossing_distance (double cd)
Definition at line 182 of file knotgraph.cpp.
Referenced by KnotView::set_crossing_distance().
void KnotGraph::set_curve_style (knot_curve_styler::style_id cs)
Definition at line 152 of file knotgraph.cpp.
Referenced by KnotView::set_curve_style().
void KnotGraph::set_cusp_angle (double ca)
Definition at line 162 of file knotgraph.cpp.
Referenced by KnotView::set_cusp_angle().
void KnotGraph::set_handle_length (double hl)
Definition at line 172 of file knotgraph.cpp.
Referenced by KnotView::set_handle_length().
void KnotGraph::set_join_style (Qt::PenJoinStyle pjs)
Definition at line 192 of file knotgraph.cpp.
Referenced by KnotView::set_join_style().
void KnotGraph::set_width (double w)
set knot path width
Definition at line 137 of file knotgraph.cpp.
Referenced by KnotView::set_width().
Member Data Documentation
double KnotGraph::crossing_distance [protected]
Definition at line 45 of file knotgraph.hpp.
Referenced by build(), get_crossing_distance(), and set_crossing_distance().
knot_curve_styler::style_id KnotGraph::curve_style [protected]
Definition at line 42 of file knotgraph.hpp.
Referenced by build(), get_curve_style(), KnotGraph(), and set_curve_style().
double KnotGraph::cusp_angle [protected]
Definition at line 43 of file knotgraph.hpp.
Referenced by build(), get_cusp_angle(), and set_cusp_angle().
QList<Edge*> KnotGraph::edges [protected]
Definition at line 39 of file knotgraph.hpp.
Referenced by add_edge(), build(), clear(), and remove_edge().
double KnotGraph::handle_length [protected]
Definition at line 44 of file knotgraph.hpp.
Referenced by build(), get_handle_length(), and set_handle_length().
QPainterPath KnotGraph::knot [protected]
Definition at line 37 of file knotgraph.hpp.
QList<Node*> KnotGraph::nodes [protected]
Definition at line 38 of file knotgraph.hpp.
Referenced by add_node(), clear(), and remove_node().
QPainterPathStroker KnotGraph::stroker [protected]
Definition at line 41 of file knotgraph.hpp.
Referenced by build(), get_join_style(), get_width(), KnotGraph(), set_join_style(), and set_width().
QList<Edge*> KnotGraph::traversed_edges [protected]
Definition at line 40 of file knotgraph.hpp.
Referenced by build().
The documentation for this class was generated from the following files:
knotgraph.hpp
knotgraph.cpp