Knotter: ColorWidget Class Reference
ColorWidget Class Reference
#include <color_widget.hpp>
Signals
void color_changed (QColor)
Public Member Functions
ColorWidget (QWidget *parent=NULL)
QColor color () const
void set_color (QColor c)
Protected Slots
void update_color (QColor c)
Protected Member Functions
void mouseReleaseEvent (QMouseEvent *)
Protected Attributes
QColorDialog color_dialog
QColor clr
Detailed Description
Definition at line 34 of file color_widget.hpp.
Constructor & Destructor Documentation
ColorWidget::ColorWidget (QWidget * parent = NULL) [inline]
Definition at line 42 of file color_widget.hpp.
Member Function Documentation
QColor ColorWidget::color () const [inline]
Definition at line 54 of file color_widget.hpp.
Referenced by ColorWidget().
void ColorWidget::color_changed (QColor _t1) [signal]
Definition at line 100 of file moc_color_widget.cpp.
Referenced by update_color().
void ColorWidget::mouseReleaseEvent (QMouseEvent *) [inline, protected]
Definition at line 67 of file color_widget.hpp.
void ColorWidget::set_color (QColor c) [inline]
Definition at line 58 of file color_widget.hpp.
void ColorWidget::update_color (QColor c) [inline, protected, slot]
Definition at line 74 of file color_widget.hpp.
Referenced by ColorWidget().
Member Data Documentation
QColor ColorWidget::clr [protected]
Definition at line 40 of file color_widget.hpp.
Referenced by color(), and update_color().
QColorDialog ColorWidget::color_dialog [protected]
Definition at line 39 of file color_widget.hpp.
Referenced by ColorWidget(), mouseReleaseEvent(), and set_color().
The documentation for this class was generated from the following files:
color_widget.hpp
moc_color_widget.cpp