Knotter: ClipboardItem Class Reference
ClipboardItem Class Reference
#include <clipboard.hpp>
Classes
struct ClipboardEdge
struct ClipboardNode
Public Member Functions
ClipboardItem (node_list nodes=node_list())
void paste (KnotView *, QPointF p) const
void copy (KnotView *)
Protected Attributes
QPointF center
QList< ClipboardNode > nodes
QList< ClipboardEdge > edges
Detailed Description
Definition at line 5 of file clipboard.hpp.
Constructor & Destructor Documentation
ClipboardItem::ClipboardItem (node_list nodes = node_list()) [explicit]
Definition at line 3 of file clipboard.cpp.
Referenced by copy().
Member Function Documentation
void ClipboardItem::copy (KnotView * kv)
Definition at line 63 of file clipboard.cpp.
Referenced by Knot_Window::copy(), and Knot_Window::cut().
void ClipboardItem::paste (KnotView * kv, QPointF p) const
Definition at line 40 of file clipboard.cpp.
Referenced by Knot_Window::paste().
Member Data Documentation
QPointF ClipboardItem::center [protected]
Definition at line 26 of file clipboard.hpp.
Referenced by ClipboardItem().
QList<ClipboardEdge> ClipboardItem::edges [protected]
Definition at line 28 of file clipboard.hpp.
Referenced by ClipboardItem(), and paste().
QList<ClipboardNode> ClipboardItem::nodes [protected]
Definition at line 27 of file clipboard.hpp.
Referenced by ClipboardItem(), and paste().
The documentation for this class was generated from the following files:
clipboard.hpp
clipboard.cpp