Knotter: KnotView Class Reference
KnotView Class Reference
#include <knotview.hpp>
Public Slots
void mode_edit_node ()
void mode_insert_edge ()
void mode_edge_chain ()
void erase_selected ()
void link_selected ()
void merge_selected ()
void select_all ()
void redraw (bool recalculate_node=true)
void reset_view ()
void zoom (double factor)
void reset_zoom ()
Signals
void mouse_moved (QPointF)
Public Member Functions
KnotView (QWidget *parent)
void do_add_node (Node *node, node_list adjl)
void do_remove_node (Node *node)
void do_move_node (Node *node, QPointF pos)
void link (Node *a, Node *b)
void unlink (Node *a, Node *b)
void do_toggle_edge (Node *a, Node *b, Edge::type_type type)
const QUndoStack & get_undo_stack () const
QUndoStack & get_undo_stack ()
void clear ()
void writeXML (QIODevice *device) const
bool readXML (QIODevice *device)
void writeSVG (QIODevice *device)
void set_width (double w)
double get_width () const
void set_pen (QPen p)
QPen get_pen () const
void set_brush (QBrush b)
QBrush get_brush () const
knot_curve_styler::style_id get_curve_style () const
void set_curve_style (knot_curve_styler::style_id)
double get_cusp_angle () const
void set_cusp_angle (double ca)
double get_handle_length () const
void set_handle_length (double hl)
double get_crossing_distance () const
void set_crossing_distance (double cd)
Qt::PenJoinStyle get_join_style () const
void set_join_style (Qt::PenJoinStyle)
Node * add_node (QPointF pos, node_list adjl=node_list())
void add_node (Node *n)
void remove_node (Node *node)
void remove_node (Node *node, node_list adjl)
void add_edge (Node *p1, Node *p2)
void remove_edge (Node *p1, Node *p2)
void move_nodes (QPointF dest)
void toggle_edge (Edge *e)
void toggle_edge_inverted (Edge *e)
void set_edge_type (Edge *e, Edge::type_type type)
node_list selected_nodes () const
snapping_grid & get_grid ()
Protected Types
enum mode_type { EDIT_NODE, INSERT_EDGE_CHAIN, INSERT_EDGE }
enum mouse_status_type {
DEFAULT, MOVING, DRAGGING, PLACING,
SELECTING
}
Protected Member Functions
QPointF get_mouse_point (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
Node * node_at (QPointF p)
Edge * edge_at (QPointF p)
void set_guide (QPointF from, QPointF to)
void unset_guide ()
void mode_change ()
Protected Attributes
mode_type mode
Node * last_node
mouse_status_type mouse_status
QPointF oldpos
node_list moved_nodes
QGraphicsLineItem * guide
QGraphicsRectItem * rubberband
QUndoStack undo_stack
KnotGraph knot
snapping_grid grid
Detailed Description
Definition at line 37 of file knotview.hpp.
Member Enumeration Documentation
enum KnotView::mode_type [protected]
Enumerator:
EDIT_NODE
INSERT_EDGE_CHAIN
INSERT_EDGE
Definition at line 42 of file knotview.hpp.
enum KnotView::mouse_status_type [protected]
Enumerator:
DEFAULT
default, mouse actions depend on mode_type
MOVING
moving existing nodes around
DRAGGING
dragging the view
PLACING
placing new items
SELECTING
dragging the rubberband
Definition at line 45 of file knotview.hpp.
Constructor & Destructor Documentation
KnotView::KnotView (QWidget * parent)
Todo:
snap to grid
insert fixed shapes
Definition at line 40 of file knotview.cpp.
Member Function Documentation
void KnotView::add_edge (Node * p1, Node * p2)
Definition at line 874 of file knotview.cpp.
Referenced by link_selected(), mousePressEvent(), mouseReleaseEvent(), ClipboardItem::paste(), readXML(), and StyleDialog::StyleDialog().
Node * KnotView::add_node (QPointF pos, node_list adjl = node_list())
Definition at line 837 of file knotview.cpp.
Referenced by merge_selected(), mousePressEvent(), ClipboardItem::paste(), readXML(), and StyleDialog::StyleDialog().
void KnotView::add_node (Node * n)
add existing node, undo command will takes ownership
Definition at line 847 of file knotview.cpp.
void KnotView::clear ()
Definition at line 482 of file knotview.cpp.
Referenced by Knot_Window::open().
void KnotView::do_add_node (Node * node, node_list adjl)
Definition at line 57 of file knotview.cpp.
Referenced by AddNode::redo(), and RemoveNode::undo().
void KnotView::do_move_node (Node * node, QPointF pos)
Definition at line 130 of file knotview.cpp.
Referenced by MoveNodes::redo(), and MoveNodes::undo().
void KnotView::do_remove_node (Node * node)
Definition at line 69 of file knotview.cpp.
Referenced by RemoveNode::redo(), and AddNode::undo().
void KnotView::do_toggle_edge (Node * a, Node * b, Edge::type_type type)
Definition at line 474 of file knotview.cpp.
Referenced by ToggleEdge::redo(), and ToggleEdge::undo().
Edge * KnotView::edge_at (QPointF p) [protected]
Definition at line 421 of file knotview.cpp.
Referenced by mousePressEvent(), and wheelEvent().
void KnotView::erase_selected () [slot]
Definition at line 981 of file knotview.cpp.
Referenced by Knot_Window::clear().
QBrush KnotView::get_brush () const
Definition at line 747 of file knotview.cpp.
Referenced by StyleDialog::on_color_color_changed(), Knot_Window::update_style_dialog(), and writeXML().
double KnotView::get_crossing_distance () const
Definition at line 785 of file knotview.cpp.
Referenced by Knot_Window::update_style_dialog().
knot_curve_styler::style_id KnotView::get_curve_style () const
Definition at line 752 of file knotview.cpp.
Referenced by Knot_Window::update_style_dialog().
double KnotView::get_cusp_angle () const
Definition at line 763 of file knotview.cpp.
Referenced by Knot_Window::update_style_dialog().
snapping_grid & KnotView::get_grid ()
Definition at line 958 of file knotview.cpp.
Referenced by Knot_Window::configure_grid(), and Knot_Window::enable_grid().
double KnotView::get_handle_length () const
Definition at line 774 of file knotview.cpp.
Referenced by Knot_Window::update_style_dialog().
Qt::PenJoinStyle KnotView::get_join_style () const
Definition at line 796 of file knotview.cpp.
Referenced by Knot_Window::update_style_dialog().
QPointF KnotView::get_mouse_point (QMouseEvent * event) [protected]
Todo:
fix this to work with dragging
Definition at line 138 of file knotview.cpp.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPen KnotView::get_pen () const
Definition at line 736 of file knotview.cpp.
Referenced by StyleDialog::on_outline_color_color_changed(), StyleDialog::on_outline_width_spinner_valueChanged(), Knot_Window::update_style_dialog(), and writeXML().
QUndoStack& KnotView::get_undo_stack () [inline]
Definition at line 80 of file knotview.hpp.
const QUndoStack& KnotView::get_undo_stack () const [inline]
Definition at line 79 of file knotview.hpp.
Referenced by Knot_Window::clear(), Knot_Window::cut(), Knot_Window::Knot_Window(), Knot_Window::open(), ClipboardItem::paste(), and Knot_Window::save().
double KnotView::get_width () const
Definition at line 724 of file knotview.cpp.
Referenced by Knot_Window::update_style_dialog(), and writeXML().
void KnotView::link (Node * a, Node * b)
Definition at line 426 of file knotview.cpp.
Referenced by do_add_node(), AddEdge::redo(), and RemoveEdge::undo().
void KnotView::link_selected () [slot]
Definition at line 994 of file knotview.cpp.
void KnotView::merge_selected () [slot]
Definition at line 1012 of file knotview.cpp.
void KnotView::mode_change () [protected]
Definition at line 829 of file knotview.cpp.
Referenced by clear(), mode_edge_chain(), mode_edit_node(), mode_insert_edge(), and mousePressEvent().
void KnotView::mode_edge_chain () [slot]
Definition at line 975 of file knotview.cpp.
Referenced by Knot_Window::mode_edge_list().
void KnotView::mode_edit_node () [slot]
Definition at line 963 of file knotview.cpp.
Referenced by KnotView(), and Knot_Window::mode_node().
void KnotView::mode_insert_edge () [slot]
Definition at line 969 of file knotview.cpp.
Referenced by Knot_Window::mode_edge().
void KnotView::mouse_moved (QPointF _t1) [signal]
Definition at line 127 of file moc_knotview.cpp.
Referenced by mouseMoveEvent().
void KnotView::mouseMoveEvent (QMouseEvent * event) [protected]
Todo:
option to turn on/off fluid knot refresh
Definition at line 288 of file knotview.cpp.
void KnotView::mousePressEvent (QMouseEvent * event) [protected]
Todo:
make auto-simmetry (top-bottom left-right, quadrature, rotation)
Definition at line 163 of file knotview.cpp.
void KnotView::mouseReleaseEvent (QMouseEvent * event) [protected]
Definition at line 340 of file knotview.cpp.
void KnotView::move_nodes (QPointF dest)
Definition at line 886 of file knotview.cpp.
Referenced by mouseReleaseEvent().
Node * KnotView::node_at (QPointF p) [protected]
Definition at line 416 of file knotview.cpp.
Referenced by mousePressEvent(), and mouseReleaseEvent().
bool KnotView::readXML (QIODevice * device)
Definition at line 595 of file knotview.cpp.
Referenced by Knot_Window::open().
void KnotView::redraw (bool recalculate_node = true) [slot]
Definition at line 1068 of file knotview.cpp.
Referenced by do_add_node(), do_move_node(), do_remove_node(), do_toggle_edge(), link(), mouseMoveEvent(), mouseReleaseEvent(), set_brush(), set_crossing_distance(), set_curve_style(), set_cusp_angle(), set_handle_length(), set_join_style(), set_pen(), set_width(), and unlink().
void KnotView::remove_edge (Node * p1, Node * p2)
Definition at line 880 of file knotview.cpp.
Referenced by mousePressEvent(), and mouseReleaseEvent().
void KnotView::remove_node (Node * node, node_list adjl)
Definition at line 866 of file knotview.cpp.
void KnotView::remove_node (Node * node)
Definition at line 853 of file knotview.cpp.
Referenced by Knot_Window::cut(), erase_selected(), and merge_selected().
void KnotView::reset_view () [slot]
Definition at line 1075 of file knotview.cpp.
void KnotView::reset_zoom () [slot]
Definition at line 1086 of file knotview.cpp.
Referenced by reset_view().
void KnotView::select_all () [slot]
Definition at line 1055 of file knotview.cpp.
Referenced by Knot_Window::clear().
node_list KnotView::selected_nodes () const
Definition at line 946 of file knotview.cpp.
Referenced by ClipboardItem::copy(), and Knot_Window::cut().
void KnotView::set_brush (QBrush b)
Definition at line 741 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_color_color_changed(), and readXML().
void KnotView::set_crossing_distance (double cd)
Definition at line 790 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_crossing_gap_spinner_valueChanged(), and readXML().
void KnotView::set_curve_style (knot_curve_styler::style_id si)
Definition at line 757 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_style_combo_activated(), readXML(), and StyleDialog::set_style_id().
void KnotView::set_cusp_angle (double ca)
Definition at line 768 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_cusp_angle_spinner_valueChanged(), and readXML().
void KnotView::set_edge_type (Edge * e, Edge::type_type type)
Definition at line 938 of file knotview.cpp.
Referenced by readXML().
void KnotView::set_guide (QPointF from, QPointF to) [protected]
Definition at line 809 of file knotview.cpp.
Referenced by do_remove_node(), mouseMoveEvent(), mousePressEvent(), and unlink().
void KnotView::set_handle_length (double hl)
Definition at line 779 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_handle_length_spinner_valueChanged(), and readXML().
void KnotView::set_join_style (Qt::PenJoinStyle pjs)
Definition at line 801 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_point_combo_activated(), and readXML().
void KnotView::set_pen (QPen p)
Bug:
pen width = 0 still renders outline (caused by Qt, width = 0 => 1px cosmetic)
Definition at line 729 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_outline_color_color_changed(), StyleDialog::on_outline_width_spinner_valueChanged(), and readXML().
void KnotView::set_width (double w)
Definition at line 718 of file knotview.cpp.
Referenced by Knot_Window::apply_style(), StyleDialog::on_knot_width_spinner_valueChanged(), and readXML().
void KnotView::toggle_edge (Edge * e)
Definition at line 906 of file knotview.cpp.
Referenced by mousePressEvent(), and wheelEvent().
void KnotView::toggle_edge_inverted (Edge * e)
Definition at line 922 of file knotview.cpp.
Referenced by wheelEvent().
void KnotView::unlink (Node * a, Node * b)
Definition at line 443 of file knotview.cpp.
Referenced by RemoveEdge::redo(), and AddEdge::undo().
void KnotView::unset_guide () [protected]
Definition at line 819 of file knotview.cpp.
Referenced by clear(), do_remove_node(), mode_change(), mouseReleaseEvent(), and unlink().
void KnotView::wheelEvent (QWheelEvent * event) [protected]
Definition at line 393 of file knotview.cpp.
void KnotView::writeSVG (QIODevice * device)
Todo:
export only path (output of knot.build())
Todo:
gen.setViewBox (?)
Definition at line 702 of file knotview.cpp.
Referenced by Knot_Window::exportSVG().
void KnotView::writeXML (QIODevice * device) const
Todo:
Grid I/O
Definition at line 502 of file knotview.cpp.
Referenced by Knot_Window::save().
void KnotView::zoom (double factor) [slot]
Definition at line 1081 of file knotview.cpp.
Referenced by wheelEvent(), Knot_Window::zoom_in(), and Knot_Window::zoom_out().
Member Data Documentation
snapping_grid KnotView::grid [protected]
Definition at line 65 of file knotview.hpp.
Referenced by get_grid(), and get_mouse_point().
QGraphicsLineItem* KnotView::guide [protected]
Definition at line 61 of file knotview.hpp.
Referenced by do_remove_node(), mouseMoveEvent(), set_guide(), unlink(), and unset_guide().
KnotGraph KnotView::knot [protected]
Definition at line 64 of file knotview.hpp.
Referenced by clear(), do_add_node(), do_remove_node(), get_brush(), get_crossing_distance(), get_curve_style(), get_cusp_angle(), get_handle_length(), get_join_style(), get_pen(), get_width(), KnotView(), link(), mouseMoveEvent(), readXML(), redraw(), set_brush(), set_crossing_distance(), set_curve_style(), set_cusp_angle(), set_handle_length(), set_join_style(), set_pen(), set_width(), unlink(), writeSVG(), and writeXML().
Node* KnotView::last_node [protected]
Definition at line 55 of file knotview.hpp.
Referenced by clear(), do_add_node(), do_remove_node(), get_mouse_point(), merge_selected(), mode_change(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and unlink().
mode_type KnotView::mode [protected]
Definition at line 54 of file knotview.hpp.
Referenced by do_remove_node(), link_selected(), merge_selected(), mode_edge_chain(), mode_edit_node(), mode_insert_edge(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and unlink().
mouse_status_type KnotView::mouse_status [protected]
Definition at line 56 of file knotview.hpp.
Referenced by get_mouse_point(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
node_list KnotView::moved_nodes [protected]
Definition at line 60 of file knotview.hpp.
Referenced by do_remove_node(), mousePressEvent(), move_nodes(), and unlink().
QPointF KnotView::oldpos [protected]
Definition at line 59 of file knotview.hpp.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and move_nodes().
QGraphicsRectItem* KnotView::rubberband [protected]
Definition at line 62 of file knotview.hpp.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QUndoStack KnotView::undo_stack [protected]
Definition at line 63 of file knotview.hpp.
Referenced by add_edge(), add_node(), clear(), do_remove_node(), erase_selected(), get_undo_stack(), link_selected(), merge_selected(), mousePressEvent(), move_nodes(), readXML(), remove_edge(), remove_node(), set_edge_type(), toggle_edge(), and toggle_edge_inverted().
The documentation for this class was generated from the following files:
knotview.hpp
knotview.cpp
moc_knotview.cpp