Knotter: snapping_grid Class Reference
snapping_grid Class Reference
#include <snapping_grid.hpp>
Public Types
enum grid_shape { SQUARE, TRIANGLE }
Public Member Functions
snapping_grid (double size=64, grid_shape shape=SQUARE, QPointF origin=QPointF(0, 0), bool enabled=true)
void snap (QPointF &p)
bool is_enabled () const
double get_size () const
grid_shape get_shape () const
QPointF get_origin () const
void enable (bool enabled)
void set_size (double size)
void set_shape (grid_shape shape)
void set_origin (QPointF origin)
Protected Attributes
double size
grid_shape shape
QPointF origin
bool enabled
Detailed Description
Definition at line 31 of file snapping_grid.hpp.
Member Enumeration Documentation
enum snapping_grid::grid_shape
Enumerator:
SQUARE
TRIANGLE
Definition at line 34 of file snapping_grid.hpp.
Constructor & Destructor Documentation
snapping_grid::snapping_grid (double size = 64, grid_shape shape = SQUARE, QPointF origin = QPointF(0,0), bool enabled = true) [explicit]
Definition at line 29 of file snapping_grid.cpp.
Member Function Documentation
void snapping_grid::enable (bool enabled)
Definition at line 95 of file snapping_grid.cpp.
Referenced by Knot_Window::enable_grid(), and GridConfig::on_buttonBox_accepted().
QPointF snapping_grid::get_origin () const
Definition at line 90 of file snapping_grid.cpp.
snapping_grid::grid_shape snapping_grid::get_shape () const
Definition at line 85 of file snapping_grid.cpp.
Referenced by Knot_Window::configure_grid(), and GridConfig::GridConfig().
double snapping_grid::get_size () const
Definition at line 80 of file snapping_grid.cpp.
Referenced by GridConfig::GridConfig().
bool snapping_grid::is_enabled () const
Definition at line 75 of file snapping_grid.cpp.
Referenced by Knot_Window::configure_grid(), and GridConfig::GridConfig().
void snapping_grid::set_origin (QPointF origin)
Definition at line 110 of file snapping_grid.cpp.
void snapping_grid::set_shape (snapping_grid::grid_shape shape)
Definition at line 105 of file snapping_grid.cpp.
Referenced by GridConfig::on_buttonBox_accepted().
void snapping_grid::set_size (double size)
Definition at line 100 of file snapping_grid.cpp.
Referenced by GridConfig::on_buttonBox_accepted().
void snapping_grid::snap (QPointF & p)
Todo:
find a way to draw the grid (lines or dots?)
Todo:
find a cool way to configure the origin (cool way != typing coordinates)
Square grid, simple enough
Triangular grid, find intersection of line1 and line2 line2 is horizontal: y = n2 * y_factor + origin.y y_factor is the height of the triangle sqrt(3)/2 * size. line1 has a 30deg slope, and x offset of n1*size + origin.x y = sqrt(3) * (x + n1*size + origin.x) They intersect in the point where y is constrained by line2, x = size/2 * n2 + size * n1
if you think of p as (x,y)+offset, you can get the expressions used below to get (x,y) from (p.x,p.y). The rounding p/size removes the offset as |offset.x| < size
Definition at line 33 of file snapping_grid.cpp.
Referenced by KnotView::get_mouse_point().
Member Data Documentation
bool snapping_grid::enabled [protected]
Definition at line 40 of file snapping_grid.hpp.
Referenced by enable(), is_enabled(), and snap().
QPointF snapping_grid::origin [protected]
Definition at line 39 of file snapping_grid.hpp.
Referenced by get_origin(), set_origin(), and snap().
grid_shape snapping_grid::shape [protected]
Definition at line 38 of file snapping_grid.hpp.
Referenced by get_shape(), set_shape(), and snap().
double snapping_grid::size [protected]
Definition at line 37 of file snapping_grid.hpp.
Referenced by get_size(), set_size(), and snap().
The documentation for this class was generated from the following files:
snapping_grid.hpp
snapping_grid.cpp