Knotter: Edge Class Reference
Edge Class Reference
#include <edge.hpp>
Public Types
enum type_type { CROSSING, WALL, HOLE, INVERTED }
enum handle_type {
NOHANDLE = 0, TOPRIGHT = 1, TOPLEFT = 2, BOTTOMLEFT = 4,
BOTTOMRIGHT = 8
}
Public Member Functions
Edge (Node *start, Node *end, type_type type=CROSSING)
QRectF boundingRect () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *, QWidget *)
bool is_vertex (const Node *) const
Node * other (const Node *which) const
Node * vertex1 () const
Node * vertex2 () const
QPainterPath shape () const
void traverse (handle_type handle)
bool traversed (handle_type handle) const
QList< QLineF > connected (double handle_length, double crossing_distance) const
handle_type not_traversed () const
bool completed () const
void reset ()
reset traversal
QLineF handle_point (handle_type handle, double handle_length, double crossing_distance) const
determine the physcal position of the handle
Public Attributes
type_type type
Protected Attributes
Node * start
Node * end
long traversed_handles
made up by or-ing handle_type constants
Detailed Description
           TOPLEFT    TOPRIGHT
                  \  /
    Node1 o-------------------o Node2
                  /  \
        BOTTOMLEFT    BOTTOMRIGHT
Definition at line 41 of file edge.hpp.
Member Enumeration Documentation
enum Edge::handle_type
Enumerator:
NOHANDLE
TOPRIGHT
TOPLEFT
BOTTOMLEFT
BOTTOMRIGHT
Definition at line 72 of file edge.hpp.
enum Edge::type_type
Enumerator:
CROSSING
WALL
HOLE
INVERTED
Definition at line 44 of file edge.hpp.
Constructor & Destructor Documentation
Edge::Edge (Node * start, Node * end, type_type type = CROSSING)
Definition at line 30 of file edge.cpp.
Member Function Documentation
QRectF Edge::boundingRect () const
Definition at line 34 of file edge.cpp.
bool Edge::completed () const
Returns:
whether all handles have been traversed
Definition at line 175 of file edge.cpp.
QList< QLineF > Edge::connected (double handle_length, double crossing_distance) const
Returns:
lines to be connected in the path
Definition at line 134 of file edge.cpp.
Referenced by KnotGraph::build().
QLineF Edge::handle_point (Edge::handle_type handle, double handle_length, double crossing_distance) const
determine the physcal position of the handle
Definition at line 186 of file edge.cpp.
Referenced by connected(), knot_curve_advanced_poly::draw_joint(), knot_curve_simple_poly::draw_joint(), knot_curve_pointed::draw_joint(), and knot_curve_ogee::draw_joint().
bool Edge::is_vertex (const Node * n) const
Definition at line 89 of file edge.cpp.
Referenced by Node::get_link().
Edge::handle_type Edge::not_traversed () const
Returns:
one of the handles that has not been traversed or NOHANDLE if all have been visited
Definition at line 161 of file edge.cpp.
Referenced by KnotGraph::build().
Node * Edge::other (const Node * which) const
Definition at line 94 of file edge.cpp.
Referenced by KnotView::do_remove_node(), Node::linked_to(), KnotView::merge_selected(), Node::next_edge(), KnotView::remove_node(), and KnotView::writeXML().
void Edge::paint (QPainter * painter, const QStyleOptionGraphicsItem * , QWidget *)
Definition at line 56 of file edge.cpp.
void Edge::reset ()
reset traversal
Postcondition:
traversed == NOHANDLE && completed() == false
Definition at line 181 of file edge.cpp.
Referenced by KnotGraph::build().
QPainterPath Edge::shape () const
Definition at line 106 of file edge.cpp.
void Edge::traverse (Edge::handle_type handle)
Definition at line 122 of file edge.cpp.
Referenced by KnotGraph::build().
bool Edge::traversed (Edge::handle_type handle) const
Definition at line 127 of file edge.cpp.
Referenced by KnotGraph::build().
Node * Edge::vertex1 () const
Definition at line 103 of file edge.cpp.
Referenced by KnotGraph::build(), ClipboardItem::ClipboardItem(), KnotView::mousePressEvent(), Node::next_edge(), KnotView::set_edge_type(), KnotView::toggle_edge(), and KnotView::toggle_edge_inverted().
Node * Edge::vertex2 () const
Definition at line 104 of file edge.cpp.
Referenced by KnotGraph::build(), ClipboardItem::ClipboardItem(), KnotView::mousePressEvent(), Node::next_edge(), KnotView::set_edge_type(), KnotView::toggle_edge(), and KnotView::toggle_edge_inverted().
Member Data Documentation
Node* Edge::end [protected]
Definition at line 48 of file edge.hpp.
Referenced by boundingRect(), handle_point(), is_vertex(), other(), paint(), shape(), and vertex2().
Node* Edge::start [protected]
Definition at line 47 of file edge.hpp.
Referenced by boundingRect(), handle_point(), is_vertex(), other(), paint(), shape(), and vertex1().
long Edge::traversed_handles [protected]
made up by or-ing handle_type constants
Definition at line 79 of file edge.hpp.
Referenced by completed(), not_traversed(), reset(), traverse(), and traversed().
type_type Edge::type
Definition at line 51 of file edge.hpp.
Referenced by connected(), KnotView::do_toggle_edge(), handle_point(), paint(), KnotView::set_edge_type(), KnotView::toggle_edge(), KnotView::toggle_edge_inverted(), and KnotView::writeXML().
The documentation for this class was generated from the following files:
edge.hpp
edge.cpp