Knotter: Node Class Reference
Node Class Reference
#include <node.hpp>
Public Member Functions
Node (QPointF position)
QRectF boundingRect () const
QRectF actualRect () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Edge * get_link (Node *other) const
void add_link (Edge *edge)
void remove_link (Edge *which)
QList< Edge * > links () const
QList< Node * > linked_to () const
TraversalInfo next_edge (Edge *edge, Edge::handle_type handle) const
find next edge end handle in traversal
Protected Attributes
QList< Edge * > edges
Static Protected Attributes
static const int radius = 5
Detailed Description
Definition at line 64 of file node.hpp.
Constructor & Destructor Documentation
Node::Node (QPointF position)
Definition at line 31 of file node.cpp.
Member Function Documentation
QRectF Node::actualRect () const
Definition at line 46 of file node.cpp.
Referenced by paint().
void Node::add_link (Edge * edge)
Definition at line 85 of file node.cpp.
Referenced by KnotView::link().
QRectF Node::boundingRect () const
Definition at line 41 of file node.cpp.
Referenced by paint().
Edge * Node::get_link (Node * other) const
Definition at line 75 of file node.cpp.
Referenced by KnotView::add_edge(), KnotView::do_toggle_edge(), KnotView::link(), KnotView::mouseReleaseEvent(), KnotView::readXML(), KnotView::remove_edge(), and KnotView::unlink().
QList< Node * > Node::linked_to () const
Definition at line 95 of file node.cpp.
Referenced by KnotView::add_node().
QList<Edge*> Node::links () const [inline]
Definition at line 85 of file node.hpp.
Referenced by ClipboardItem::ClipboardItem(), KnotView::do_remove_node(), KnotView::merge_selected(), KnotView::remove_node(), and KnotView::writeXML().
TraversalInfo Node::next_edge (Edge * edge, Edge::handle_type handle) const
find next edge end handle in traversal
Modifies the parameters so that the restult will be the next edge/handle pair.
Definition at line 106 of file node.cpp.
Referenced by KnotGraph::build().
void Node::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
Definition at line 51 of file node.cpp.
void Node::remove_link (Edge * which)
Definition at line 90 of file node.cpp.
Referenced by KnotView::do_remove_node(), and KnotView::unlink().
Member Data Documentation
QList<Edge*> Node::edges [protected]
Definition at line 68 of file node.hpp.
Referenced by add_link(), get_link(), linked_to(), links(), next_edge(), and remove_link().
const int Node::radius = 5 [static, protected]
Definition at line 67 of file node.hpp.
Referenced by actualRect(), and boundingRect().
The documentation for this class was generated from the following files:
node.hpp
node.cpp