Knotter: knot_curve_styler Struct Reference
knot_curve_styler Struct Reference
#include <knot_curve_style.hpp>
Public Types
typedef long style_id
Static Public Member Functions
static knot_curve_style * style (style_id id)
static knot_curve_style * style (QString name)
static style_id register_style (knot_curve_style *style)
takes ownership
static void register_alias (style_id id, QString name)
static style_id idof (QString name)
static QString name (style_id id)
Private Member Functions
knot_curve_styler ()
~knot_curve_styler ()
Static Private Attributes
static knot_curve_styler singleton
static QMap< style_id,
knot_curve_style * > styles
static QMap< QString, style_id > names
Detailed Description
Definition at line 90 of file knot_curve_style.hpp.
Member Typedef Documentation
typedef long knot_curve_styler::style_id
Definition at line 92 of file knot_curve_style.hpp.
Constructor & Destructor Documentation
knot_curve_styler::knot_curve_styler () [private]
Definition at line 207 of file knot_curve_style.cpp.
knot_curve_styler::~knot_curve_styler () [private]
Definition at line 215 of file knot_curve_style.cpp.
Member Function Documentation
knot_curve_styler::style_id knot_curve_styler::idof (QString name) [static]
Definition at line 194 of file knot_curve_style.cpp.
Referenced by KnotGraph::KnotGraph(), KnotView::readXML(), and StyleDialog::StyleDialog().
QString knot_curve_styler::name (knot_curve_styler::style_id id) [static]
Definition at line 201 of file knot_curve_style.cpp.
Referenced by idof(), register_alias(), style(), and KnotView::writeXML().
void knot_curve_styler::register_alias (knot_curve_styler::style_id id, QString name) [static]
Definition at line 189 of file knot_curve_style.cpp.
Referenced by knot_curve_styler().
knot_curve_styler::style_id knot_curve_styler::register_style (knot_curve_style * style) [static]
takes ownership
Definition at line 182 of file knot_curve_style.cpp.
Referenced by knot_curve_styler().
knot_curve_style * knot_curve_styler::style (style_id id) [static]
Definition at line 172 of file knot_curve_style.cpp.
Referenced by KnotGraph::build(), and register_style().
knot_curve_style * knot_curve_styler::style (QString name) [static]
Definition at line 177 of file knot_curve_style.cpp.
Member Data Documentation
QMap< QString, knot_curve_styler::style_id > knot_curve_styler::names [static, private]
Definition at line 109 of file knot_curve_style.hpp.
Referenced by idof(), name(), register_alias(), and style().
knot_curve_styler knot_curve_styler::singleton [static, private]
Definition at line 107 of file knot_curve_style.hpp.
QMap< knot_curve_styler::style_id, knot_curve_style * > knot_curve_styler::styles [static, private]
Definition at line 108 of file knot_curve_style.hpp.
Referenced by idof(), register_style(), style(), and ~knot_curve_styler().
The documentation for this struct was generated from the following files:
knot_curve_style.hpp
knot_curve_style.cpp